# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ccs-backend
    restart: unless-stopped
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - ccs-network

  postgres:
    image: postgres:15-alpine
    container_name: ccs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ccs_db
      POSTGRES_USER: ccs_user
      POSTGRES_PASSWORD: ccs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ccs-network

  redis:
    image: redis:7-alpine
    container_name: ccs-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ccs-network

volumes:
  postgres_data:
  redis_data:

networks:
  ccs-network:
    driver: bridge 